# Generated by Django 3.1.2 on 2021-03-23 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start', models.IntegerField()),
                ('class_path', models.TextField()),
                ('end', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classs',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_days', models.FloatField()),
                ('comments', models.IntegerField()),
                ('absolute_path', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mccabe', models.IntegerField()),
                ('committers_count', models.IntegerField()),
                ('change_frequency', models.IntegerField()),
                ('ratio_comment_to_code', models.FloatField()),
                ('sloc', models.IntegerField()),
                ('language', models.CharField(max_length=255)),
                ('relative_path', models.TextField()),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('method_path', models.TextField()),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_metrics.class')),
            ],
            options={
                'verbose_name': 'Method',
                'verbose_name_plural': 'Methods',
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start', models.IntegerField()),
                ('function_path', models.TextField()),
                ('end', models.IntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_metrics.file')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_metrics.file'),
        ),
    ]
